// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBo4jAyhNEWC5hXozJGJ-KJCJHHvNfoHI',
    appId: '1:319552113597:web:805a839fe52ace5acda0d4',
    messagingSenderId: '319552113597',
    projectId: 'mockuniqlo',
    authDomain: 'mockuniqlo.firebaseapp.com',
    storageBucket: 'mockuniqlo.firebasestorage.app',
    measurementId: 'G-MXY920M5QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOFDQEtt1Z5W1Pzd18UmBsVyj-Bag4GY',
    appId: '1:319552113597:android:294de828052d6303cda0d4',
    messagingSenderId: '319552113597',
    projectId: 'mockuniqlo',
    storageBucket: 'mockuniqlo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXib2tp3KXOpw4s9XBZLHZuXuI-qn95pQ',
    appId: '1:319552113597:ios:ff19e73d4a711368cda0d4',
    messagingSenderId: '319552113597',
    projectId: 'mockuniqlo',
    storageBucket: 'mockuniqlo.firebasestorage.app',
    iosBundleId: 'com.example.eCommApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXib2tp3KXOpw4s9XBZLHZuXuI-qn95pQ',
    appId: '1:319552113597:ios:ff19e73d4a711368cda0d4',
    messagingSenderId: '319552113597',
    projectId: 'mockuniqlo',
    storageBucket: 'mockuniqlo.firebasestorage.app',
    iosBundleId: 'com.example.eCommApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBo4jAyhNEWC5hXozJGJ-KJCJHHvNfoHI',
    appId: '1:319552113597:web:64711eb1c6cfe1d0cda0d4',
    messagingSenderId: '319552113597',
    projectId: 'mockuniqlo',
    authDomain: 'mockuniqlo.firebaseapp.com',
    storageBucket: 'mockuniqlo.firebasestorage.app',
    measurementId: 'G-D7Y6Y49NX9',
  );
}
